// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvLKj2GCHI0H75uBim47teD4RIutSPuTc',
    appId: '1:756428773911:web:2fb5f1c94ed7ae02781a52',
    messagingSenderId: '756428773911',
    projectId: 'fir-exercicio-caio',
    authDomain: 'fir-exercicio-caio.firebaseapp.com',
    storageBucket: 'fir-exercicio-caio.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuPQLHliMl1xwu8cHtKUVpiIViMx9bvts',
    appId: '1:756428773911:android:5c7db4f464feca1e781a52',
    messagingSenderId: '756428773911',
    projectId: 'fir-exercicio-caio',
    storageBucket: 'fir-exercicio-caio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuNX7UquVd1bi7GFDxJYyv8I7tH6V3ylA',
    appId: '1:756428773911:ios:a106fafe98a5cfd0781a52',
    messagingSenderId: '756428773911',
    projectId: 'fir-exercicio-caio',
    storageBucket: 'fir-exercicio-caio.appspot.com',
    iosClientId: '756428773911-qvfkp2a21quprv5mpbhjvfhkgo5m1p9r.apps.googleusercontent.com',
    iosBundleId: 'com.projectfirebasedeiro.firebaseExercice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuNX7UquVd1bi7GFDxJYyv8I7tH6V3ylA',
    appId: '1:756428773911:ios:a106fafe98a5cfd0781a52',
    messagingSenderId: '756428773911',
    projectId: 'fir-exercicio-caio',
    storageBucket: 'fir-exercicio-caio.appspot.com',
    iosClientId: '756428773911-qvfkp2a21quprv5mpbhjvfhkgo5m1p9r.apps.googleusercontent.com',
    iosBundleId: 'com.projectfirebasedeiro.firebaseExercice',
  );
}
